from enum import Enum


class OrderState(str, Enum):
    WELCOME = "WELCOME"
    SELECT_PRINT_TYPE = "SELECT_PRINT_TYPE"
    SELECT_PAPER_SIZE = "SELECT_PAPER_SIZE"
    SELECT_COPIES = "SELECT_COPIES"
    SELECT_EXTRAS = "SELECT_EXTRAS"
    UPLOAD_FILE = "UPLOAD_FILE"
    ANALYZING_FILE = "ANALYZING_FILE"
    QUOTE_REVIEW = "QUOTE_REVIEW"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_PROOF = "PAYMENT_PROOF"
    PAYMENT_VERIFYING = "PAYMENT_VERIFYING"
    CONFIRMED = "CONFIRMED"
    DONE = "DONE"
